import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{vue,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--color-bg)',
        surface: 'var(--color-surface)',
        'surface-hover': 'var(--color-surface-hover)',
        text: 'var(--color-text)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        accent: 'var(--color-accent)',
        'accent-hover': 'var(--color-accent-hover)',
        'accent-soft': 'var(--color-accent-soft)',
        success: 'var(--color-success)',
        'success-soft': 'var(--color-success-soft)',
        warning: 'var(--color-warning)',
        'warning-soft': 'var(--color-warning-soft)',
        error: 'var(--color-error)',
        'error-soft': 'var(--color-error-soft)',
        info: 'var(--color-info)',
        'info-soft': 'var(--color-info-soft)',
        'activity-bg': 'var(--color-activity-bg)',
        'activity-active': 'var(--color-activity-active)',
        'sidebar-bg': 'var(--color-sidebar-bg)',
        'sidebar-border': 'var(--color-sidebar-border)',
        'glass-bg': 'var(--color-glass-bg)',
        'glass-border': 'var(--color-glass-border)',
        overlay: 'var(--color-overlay)',
        'overlay-light': 'var(--color-overlay-light)',
        background: 'var(--color-bg)',
        foreground: 'var(--color-text)',
        muted: 'var(--color-surface-hover)',
        'muted-foreground': 'var(--color-text-secondary)',
        card: 'var(--color-surface)',
        'card-foreground': 'var(--color-text)',
        popover: 'var(--color-surface)',
        'popover-foreground': 'var(--color-text)',
        destructive: 'var(--color-error)',
        'destructive-foreground': '#ffffff',
        ring: 'var(--color-focus-ring)',
        input: 'var(--color-surface)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
      },
      fontSize: {
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
      },
      fontFamily: {
        sans: 'var(--font-sans)',
        mono: 'var(--font-mono)',
        display: 'var(--font-display)',
      },
      spacing: {
        'activity-bar': 'var(--activity-bar-width)',
        sidebar: 'var(--sidebar-width)',
      },
    },
  },
  plugins: [],
}
